// Generated by `bun scripts/audit.ts`. Do not edit by hand.
//
// The last Lighthouse run, which System Info prints. See the script for why this is committed
// rather than measured in the build, and why the route and preset are the unflattering ones.

export const LIGHTHOUSE = {
	/** The day the audit ran, `YYYY-MM-DD`, off the report's own `fetchTime`. */
	measured: '2026-07-31',
	/** What was audited. Both are part of the reading: a score with no route is not a number. */
	route: '/',
	preset: 'mobile',
	scores: {
		performance: 69,
		accessibility: 100,
		'best-practices': 100,
		seo: 100
	}
} as const;
