// Generated by `bun scripts/mask-wallpaper.ts`. Do not edit by hand.
//
// Where every band's mask lives, and the box it is drawn in. The href is content-addressed, so a
// re-traced scene lands under a new name and the immutable rule in `_headers` stays honest.
//
// `w` and `h` come from the source viewBox and become the layer's `aspect-ratio`. An inline SVG
// carried its own ratio and got its height from `height: auto`; a div wearing a mask has neither,
// so the number has to travel with the file.

/** What a layer is painted with. `ramp` is the crest-to-base gradient, the other two are flat. */
export type Paint = 'ramp' | 'crest' | 'base';

export type Layer = { paint: Paint; href: string };

/** One band's art: its source box, and the layers that stack inside it, back to front. */
export type Art = { w: number; h: number; layers: Layer[] };

export const ART: Record<string, Record<string, Art>> = {
	'abstract-symbols-1': {
		far: {
			w: 3200,
			h: 2000,
			layers: [
				{
					paint: 'ramp',
					href: '/wallpapers/abstract-symbols-1/far.efce3607.svg'
				}
			]
		},
		mid: {
			w: 3200,
			h: 2000,
			layers: [
				{
					paint: 'ramp',
					href: '/wallpapers/abstract-symbols-1/mid.73e1c024.svg'
				}
			]
		},
		near: {
			w: 3200,
			h: 2000,
			layers: [
				{
					paint: 'ramp',
					href: '/wallpapers/abstract-symbols-1/near.33b3d621.svg'
				}
			]
		}
	},
	'circuit-bottom': {
		far: {
			w: 3053,
			h: 1003,
			layers: [
				{
					paint: 'ramp',
					href: '/wallpapers/circuit-bottom/far.4e45bd7f.svg'
				}
			]
		},
		mid: {
			w: 3053,
			h: 975,
			layers: [
				{
					paint: 'ramp',
					href: '/wallpapers/circuit-bottom/mid.b9cf2b44.svg'
				}
			]
		},
		near: {
			w: 3053,
			h: 724,
			layers: [
				{
					paint: 'ramp',
					href: '/wallpapers/circuit-bottom/near.da13e32b.svg'
				}
			]
		}
	},
	'circuit-streak': {
		far: {
			w: 2807,
			h: 1604,
			layers: [
				{
					paint: 'ramp',
					href: '/wallpapers/circuit-streak/far.eb03551e.svg'
				}
			]
		},
		near: {
			w: 2807,
			h: 1604,
			layers: [
				{
					paint: 'ramp',
					href: '/wallpapers/circuit-streak/near.00fff2fe.svg'
				}
			]
		}
	},
	grove: {
		far: {
			w: 1600,
			h: 394.7,
			layers: [
				{
					paint: 'ramp',
					href: '/wallpapers/grove/far.d3ee148f.svg'
				}
			]
		},
		'far-1': {
			w: 1600,
			h: 425,
			layers: [
				{
					paint: 'ramp',
					href: '/wallpapers/grove/far-1.e44184f5.svg'
				}
			]
		},
		mid: {
			w: 1600,
			h: 304.3,
			layers: [
				{
					paint: 'ramp',
					href: '/wallpapers/grove/mid.6b555b8a.svg'
				}
			]
		},
		'mid-1': {
			w: 1600,
			h: 351.3,
			layers: [
				{
					paint: 'ramp',
					href: '/wallpapers/grove/mid-1.0c1600ac.svg'
				}
			]
		},
		'mid-2': {
			w: 1600,
			h: 332.5,
			layers: [
				{
					paint: 'ramp',
					href: '/wallpapers/grove/mid-2.9065b8eb.svg'
				}
			]
		},
		near: {
			w: 1600,
			h: 252.3,
			layers: [
				{
					paint: 'ramp',
					href: '/wallpapers/grove/near.932454c7.svg'
				}
			]
		},
		'near-1': {
			w: 1600,
			h: 266.5,
			layers: [
				{
					paint: 'ramp',
					href: '/wallpapers/grove/near-1.230c6bed.svg'
				}
			]
		}
	},
	hive: {
		far: {
			w: 5000,
			h: 3000,
			layers: [
				{
					paint: 'ramp',
					href: '/wallpapers/hive/far.624b5f4a.svg'
				},
				{
					paint: 'base',
					href: '/wallpapers/hive/far.cf95611e.svg'
				},
				{
					paint: 'crest',
					href: '/wallpapers/hive/far.3c515bc2.svg'
				}
			]
		},
		mid: {
			w: 5000,
			h: 3000,
			layers: [
				{
					paint: 'ramp',
					href: '/wallpapers/hive/mid.6312d289.svg'
				},
				{
					paint: 'base',
					href: '/wallpapers/hive/mid.c98f86c7.svg'
				},
				{
					paint: 'crest',
					href: '/wallpapers/hive/mid.3a7b8d9e.svg'
				}
			]
		},
		near: {
			w: 5000,
			h: 3000,
			layers: [
				{
					paint: 'ramp',
					href: '/wallpapers/hive/near.ea2ee68b.svg'
				},
				{
					paint: 'base',
					href: '/wallpapers/hive/near.ce129b9e.svg'
				},
				{
					paint: 'crest',
					href: '/wallpapers/hive/near.2cbb3e01.svg'
				}
			]
		}
	},
	'night-scene': {
		far: {
			w: 4200,
			h: 1301,
			layers: [
				{
					paint: 'ramp',
					href: '/wallpapers/night-scene/far.92385cc0.svg'
				}
			]
		},
		mid: {
			w: 4200,
			h: 877,
			layers: [
				{
					paint: 'ramp',
					href: '/wallpapers/night-scene/mid.18ae2586.svg'
				}
			]
		},
		near: {
			w: 4200,
			h: 2453,
			layers: [
				{
					paint: 'ramp',
					href: '/wallpapers/night-scene/near.282d9ae4.svg'
				}
			]
		}
	},
	'pixel-brush': {
		far: {
			w: 2600,
			h: 1600,
			layers: [
				{
					paint: 'ramp',
					href: '/wallpapers/pixel-brush/far.d5fe8ceb.svg'
				}
			]
		},
		mid: {
			w: 2600,
			h: 1600,
			layers: [
				{
					paint: 'ramp',
					href: '/wallpapers/pixel-brush/mid.d561a71d.svg'
				}
			]
		},
		near: {
			w: 2600,
			h: 1600,
			layers: [
				{
					paint: 'ramp',
					href: '/wallpapers/pixel-brush/near.3a6dd322.svg'
				}
			]
		}
	}
};
