/**
 * The Lighthouse audit, and the numbers System Info prints.
 *
 * 4.5 built that window on the rule that every reading in it is measured or injected and never
 * typed in, and left one hole: a score cannot be pulled at build time without running Lighthouse
 * inside the build, and a hardcoded 100 is precisely the number the window exists not to print.
 * This is that hole closed, the same way `gen-palette.ts` and `paint-wallpaper.ts` close theirs:
 * a script run by hand that writes a generated module the repo then commits.
 *
 * Not run in CI, and that is deliberate rather than lazy. Cloudflare Workers Builds has no Chrome
 * and no server to point one at, so an audit in the build would either be skipped silently or fail
 * the deploy over a number that is not a correctness property. Run it against a local preview when
 * something that could move the numbers has moved, and commit what comes back.
 *
 *   bun run build && bun run preview      # in one shell
 *   bun scripts/audit.ts                  # in another
 *
 * `/` rather than a content route, and mobile rather than desktop, because both of those are the
 * unflattering choice and this file is worthless the moment it starts flattering. The desktop is
 * the page System Info is running inside, and it is the heaviest page on the site; mobile is
 * Lighthouse's own default and its throttling is the harsher of the two. A number picked to look
 * good is a number nobody can act on.
 */

const BASE = process.env.BASE ?? 'http://localhost:4173';
const ROUTE = '/';
const PRESET = 'mobile';

const OUT = new URL('../src/lib/lighthouse.ts', import.meta.url);

/** The four Lighthouse reports as categories, in the order the window lists them. */
const CATEGORIES = ['performance', 'accessibility', 'best-practices', 'seo'] as const;

const proc = Bun.spawn(
	[
		'bunx',
		'--yes',
		'lighthouse@12',
		`${BASE}${ROUTE}`,
		'--quiet',
		'--output=json',
		'--output-path=stdout',
		'--chrome-flags=--headless=new --no-sandbox',
		`--only-categories=${CATEGORIES.join(',')}`
	],
	{ stdout: 'pipe', stderr: 'inherit' }
);

const report = await new Response(proc.stdout).json();
if ((await proc.exited) !== 0) throw new Error('lighthouse did not finish');

const scores: Record<string, number> = {};
for (const key of CATEGORIES) {
	const score = report.categories?.[key]?.score;
	// A null score is a category Lighthouse could not compute, which would otherwise land in the
	// window as a confident 0. Stopping is the honest failure.
	if (typeof score !== 'number') throw new Error(`${key} came back with no score`);
	scores[key] = Math.round(score * 100);
}

/** The audit's own day, from the report rather than from a clock this script reads. */
const measured = String(report.fetchTime).slice(0, 10);

const body = `// Generated by \`bun scripts/audit.ts\`. Do not edit by hand.
//
// The last Lighthouse run, which System Info prints. See the script for why this is committed
// rather than measured in the build, and why the route and preset are the unflattering ones.

export const LIGHTHOUSE = {
	/** The day the audit ran, \`YYYY-MM-DD\`, off the report's own \`fetchTime\`. */
	measured: '${measured}',
	/** What was audited. Both are part of the reading: a score with no route is not a number. */
	route: '${ROUTE}',
	preset: '${PRESET}',
	scores: {
${CATEGORIES.map((key) => `\t\t'${key}': ${scores[key]}`).join(',\n')}
	}
} as const;
`;

await Bun.write(OUT, body);
console.log(`${ROUTE} (${PRESET}) on ${measured}`);
for (const key of CATEGORIES) console.log(`  ${key.padEnd(16)}${String(scores[key]).padStart(4)}`);
